// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.1
// source: schema/message.proto

package schema

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Command int32

const (
	Command_GET_INPUT_POSITION    Command = 0
	Command_RETURN_INPUT_POSITION Command = 1
	Command_REGISTER_PROMPT       Command = 2
	Command_PROMPT_FINISHED       Command = 3
)

// Enum value maps for Command.
var (
	Command_name = map[int32]string{
		0: "GET_INPUT_POSITION",
		1: "RETURN_INPUT_POSITION",
		2: "REGISTER_PROMPT",
		3: "PROMPT_FINISHED",
	}
	Command_value = map[string]int32{
		"GET_INPUT_POSITION":    0,
		"RETURN_INPUT_POSITION": 1,
		"REGISTER_PROMPT":       2,
		"PROMPT_FINISHED":       3,
	}
)

func (x Command) Enum() *Command {
	p := new(Command)
	*p = x
	return p
}

func (x Command) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Command) Descriptor() protoreflect.EnumDescriptor {
	return file_schema_message_proto_enumTypes[0].Descriptor()
}

func (Command) Type() protoreflect.EnumType {
	return &file_schema_message_proto_enumTypes[0]
}

func (x Command) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Command.Descriptor instead.
func (Command) EnumDescriptor() ([]byte, []int) {
	return file_schema_message_proto_rawDescGZIP(), []int{0}
}

type Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Command Command `protobuf:"varint,1,opt,name=command,proto3,enum=Command" json:"command,omitempty"`
	X       int32   `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`
	Y       int32   `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`
	Prompt  string  `protobuf:"bytes,4,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Url     string  `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *Message) Reset() {
	*x = Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schema_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_schema_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_schema_message_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetCommand() Command {
	if x != nil {
		return x.Command
	}
	return Command_GET_INPUT_POSITION
}

func (x *Message) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Message) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Message) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *Message) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

var File_schema_message_proto protoreflect.FileDescriptor

var file_schema_message_proto_rawDesc = []byte{
	0x0a, 0x14, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x73, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x22, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x08, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x07, 0x63, 0x6f,
	0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01,
	0x79, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x2a, 0x66, 0x0a, 0x07, 0x43,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x16, 0x0a, 0x12, 0x47, 0x45, 0x54, 0x5f, 0x49, 0x4e,
	0x50, 0x55, 0x54, 0x5f, 0x50, 0x4f, 0x53, 0x49, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x00, 0x12, 0x19,
	0x0a, 0x15, 0x52, 0x45, 0x54, 0x55, 0x52, 0x4e, 0x5f, 0x49, 0x4e, 0x50, 0x55, 0x54, 0x5f, 0x50,
	0x4f, 0x53, 0x49, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x01, 0x12, 0x13, 0x0a, 0x0f, 0x52, 0x45, 0x47,
	0x49, 0x53, 0x54, 0x45, 0x52, 0x5f, 0x50, 0x52, 0x4f, 0x4d, 0x50, 0x54, 0x10, 0x02, 0x12, 0x13,
	0x0a, 0x0f, 0x50, 0x52, 0x4f, 0x4d, 0x50, 0x54, 0x5f, 0x46, 0x49, 0x4e, 0x49, 0x53, 0x48, 0x45,
	0x44, 0x10, 0x03, 0x42, 0x31, 0x5a, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x46, 0x72, 0x61, 0x6e, 0x6b, 0x2d, 0x4d, 0x61, 0x79, 0x65, 0x72, 0x2f, 0x69, 0x6e,
	0x6e, 0x6f, 0x2d, 0x6c, 0x61, 0x62, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f,
	0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_schema_message_proto_rawDescOnce sync.Once
	file_schema_message_proto_rawDescData = file_schema_message_proto_rawDesc
)

func file_schema_message_proto_rawDescGZIP() []byte {
	file_schema_message_proto_rawDescOnce.Do(func() {
		file_schema_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_schema_message_proto_rawDescData)
	})
	return file_schema_message_proto_rawDescData
}

var file_schema_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_schema_message_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_schema_message_proto_goTypes = []interface{}{
	(Command)(0),    // 0: Command
	(*Message)(nil), // 1: Message
}
var file_schema_message_proto_depIdxs = []int32{
	0, // 0: Message.command:type_name -> Command
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_schema_message_proto_init() }
func file_schema_message_proto_init() {
	if File_schema_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_schema_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_schema_message_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_schema_message_proto_goTypes,
		DependencyIndexes: file_schema_message_proto_depIdxs,
		EnumInfos:         file_schema_message_proto_enumTypes,
		MessageInfos:      file_schema_message_proto_msgTypes,
	}.Build()
	File_schema_message_proto = out.File
	file_schema_message_proto_rawDesc = nil
	file_schema_message_proto_goTypes = nil
	file_schema_message_proto_depIdxs = nil
}
