require("env")
local yab = require("yab")
yab.setenv("CREDENTIALS_LOCATION","/Users/Shared/veritas/serviceAccountKey.json")
yab.setenv("FULLSCREEN", "true")
yab.cd("server", function()
    os.execute("go run ./cmd/server")
end)
